#  _______ _ _ _______    _            _____
# |__   __(_) |__   __|  | |          / ____|
# | |   _| | _| | ___ | | ________| |  __  __ _ _ __ ___   ___
# | |  | | |/ / |/ _ \| |/ /______| | |_ |/ _` | '_ ` _ \ / _ \
# | |  | |   <| | (_) |   <       | |__| | (_| | | | | | |  __/
# |_|  |_|_|\_\_|\___/|_|\_\       \_____|\__,_|_| |_| |_|\___|
#
# Made by kuezese

# Konfiguracja licencji
license: WXYZA-BCDEF-GHIJK-LMNOP

# GÅ‚Ã³wna konfiguracja pluginu
arena-size: 100 # Rozmiar areny gry
countdown-time: 10 # Czas odliczania do zakoÅ„czenia gry

# Konfiguracja Spawnowania MobÃ³w
mob-start-amount: 50 # Liczba mobÃ³w poczÄ…tkowo na arenie lub po restarcie
mob-spawn-radius: 10 # PromieÅ„ wokÃ³Å‚ gracza, w ktÃ³rym moby mogÄ… siÄ™ spawnowaÄ‡

# Konfiguracja Tablicy WynikÃ³w
scoreboard-header: '&c&lTik&f&lTok &7&lGame' # NagÅ‚Ã³wek tablicy wynikÃ³w
scoreboard-contents:
  - '&1' # Separator sekcji
  - '&aâ˜ &7Wynik: &a{PLAYER-SCORE} &7- &a{VIEWER-SCORE}' # WyÅ›wietlanie wyniku gracza i widza
  - '&aâœ½ &7Liczba MobÃ³w: &a{MOBS}' # WyÅ›wietlanie liczby aktualnych mobÃ³w na arenie
  - '&2' # Separator sekcji
  - '&aâœª &7Ostatni Gifter: &a{LAST-GIFTER}' # WyÅ›wietlanie nazwy ostatniej osoby obdarowujÄ…cej giftem
  - '&aâœŽ &7Ostatni Follower: &a{LAST-FOLLOWER}' # WyÅ›wietlanie nazwy ostatniej obserwujÄ…cej osoby
  - '&aðŸ”¥ &7PolubieÅ„: &a{LIKES}' # WyÅ›wietlanie liczby polubieÅ„
  - '&aâœ§ &7Widzowie: &a{VIEWERS}' # WyÅ›wietlanie liczby widzÃ³w
  - '&3' # Separator sekcji

# Konfiguracja chatu
show-chat-from-tiktok: true # WÅ‚Ä…czenie/wyÅ‚Ä…czenie wyÅ›wietlania wiadomoÅ›ci z chatu na TikToku
show-joins-from-tiktok: true # WÅ‚Ä…czenie/wyÅ‚Ä…czenie wyÅ›wietlania doÅ‚Ä…czeÅ„ na TikToku
show-follows-from-tiktok: true # WÅ‚Ä…czenie/wyÅ‚Ä…czenie wyÅ›wietlania obserwacji na TikToku
show-likes-from-tiktok: true # WÅ‚Ä…czenie/wyÅ‚Ä…czenie wyÅ›wietlania polubieÅ„ na TikToku

# Konfiguracja giftÃ³w
announce-gifts-on-chat: true # WÅ‚Ä…czenie/wyÅ‚Ä…czenie wyÅ›wietlania informacji o giftach na chacie
announce-gifts-on-title: true # WÅ‚Ä…czenie/wyÅ‚Ä…czenie wyÅ›wietlania informacji o giftach jako title

# Konfiguracja wiadomoÅ›ci
game-prefix: '&8[&cGAME&8]' # Prefiks dla wiadomoÅ›ci zwiÄ…zanych z grÄ…
chat-prefix: '&8[&cCHAT&8]' # Prefiks dla wiadomoÅ›ci chatu
chat-format: '{PREFIX} &7{PLAYER} &8Â» &f{MESSAGE}' # Format wiadomoÅ›ci chatu (zmienna {PLAYER} to nazwa gracza, {MESSAGE} to treÅ›Ä‡ wiadomoÅ›ci)
game-reset: '{PREFIX} &7Gra zostaÅ‚a &azresetowana&7.' # Komunikat o zresetowaniu gry
game-stop: '{PREFIX} &7Gra zostaÅ‚a &azatrzymana&7.' # Komunikat o zatrzymaniu gry
player-join: "{PREFIX} &a+ &7{PLAYER}" # Komunikat o doÅ‚Ä…czeniu gracza
player-quit: "{PREFIX} &c- &7{PLAYER}" # Komunikat o opuszczeniu gracza
gift-chat-prefix: '&8[&cGIFT&8]' # Prefiks dla giftÃ³w na chacie
gift-chat-message: '{PREFIX} &a{PLAYER} &7wysÅ‚aÅ‚ &a{GIFT} x{AMOUNT}&7.' # Komunikat o otrzymaniu giftu na chacie
gift-title: '&a&lGIFT' # TytuÅ‚ wyÅ›wietlany przy giftach
gift-subtitle: '&a{PLAYER} &7wysÅ‚aÅ‚ &a{GIFT} x{AMOUNT}&7.' # PodtytuÅ‚ wyÅ›wietlany przy giftach
countdown-title: "&a&lODLICZANIE" # TytuÅ‚ wyÅ›wietlany podczas odliczania
countdown-subtitle: "&a&l{TIME}" # PodtytuÅ‚ wyÅ›wietlany podczas odliczania
countdown-cancel-title: "&a&lODLICZANIE ANULOWANE" # TytuÅ‚ wyÅ›wietlany, gdy odliczanie zostanie anulowane
countdown-cancel-subtitle: "&a{PLAYER} &7wysÅ‚aÅ‚ &a{GIFT} x{AMOUNT}" # PodtytuÅ‚ wyÅ›wietlany, gdy odliczanie zostanie anulowane
player-win-title: "&a&lZWYCIÄ˜STWO" # TytuÅ‚ wyÅ›wietlany przy zwyciÄ™stwie gracza
player-win-subtitle: "&a&lGracz wygrywa!" # PodtytuÅ‚ wyÅ›wietlany przy zwyciÄ™stwie gracza
player-lose-title: "&c&lPORAZKA" # TytuÅ‚ wyÅ›wietlany przy przegranej gracza
player-lose-subtitle: "&aWidzowie zwyciÄ™Å¼ajÄ…!" # PodtytuÅ‚ wyÅ›wietlany przy przegranej gracza

# Konfiguracja giftÃ³w TikTok
gifts:
  'Rose': # Nazwa giftu "Rose"
    - 'addmob Zombie 1 {GIFTER}' # Komenda dla giftu "Rose" - dodaje 1 moba "Zombie" z nickiem osoby dajÄ…cej prezent ({GIFTER})
  'Panda': # Nazwa giftu "Panda"
    - 'addmob Skeleton 3 {GIFTER}' # Komenda dla giftu "Panda" - dodaje 3 moby "Skeleton" z nickiem osoby dajÄ…cej prezent ({GIFTER})
  'Perfume': # Nazwa giftu "Perfume"
    - 'addmob Zombie 21 {GIFTER}' # Komenda dla giftu "Perfume" - dodaje 21 mobÃ³w "Zombie" z nickiem osoby dajÄ…cej prezent ({GIFTER})
  'Doughnut': # Nazwa giftu "Doughnut"
    - 'addmob Skeleton 20 {GIFTER}' # Komenda dla giftu "Doughnut" - dodaje 20 mobÃ³w "Skeleton" z nickiem osoby dajÄ…cej prezent ({GIFTER})
  'Cap': # Nazwa giftu "Cap"
    - 'addmob Zombie 50 {GIFTER}' # Komenda dla giftu "Cap" - dodaje 50 mobÃ³w "Zombie" z nickiem osoby dajÄ…cej prezent ({GIFTER})
    - 'addmob Skeleton 50 {GIFTER}' # Dodatkowa komenda dla giftu "Cap" - dodaje 50 mobÃ³w "Skeleton" z nickiem osoby dajÄ…cej prezent ({GIFTER})
  'TikTok': # Nazwa giftu "TikTok"
    - 'strength 5 1' # Komenda dla giftu "TikTok" - daje efekt "strength" o poziomie 5 na 1 sekundÄ™
  'Lollipop': # Nazwa giftu "Lollipop"
    - 'heal' # Komenda dla giftu "Lollipop" - leczy gracza
    - 'give @a golden_apple 2' # Dodatkowa komenda dla giftu "Lollipop" - daje 2 zÅ‚ote jabÅ‚ka
  'Confetti': # Nazwa giftu "Confetti"
    - 'repairall' # Komenda dla giftu "Confetti" - naprawia wszystkie przedmioty w ekwipunku graczy
    - 'give @a enchanted_golden_apple 2' # Dodatkowa komenda dla giftu "Confetti" - daje 2 zaklÄ™te zÅ‚ote jabÅ‚ka
  'Love You': # Nazwa giftu "Love You"
    - 'addmaxhp 10' # Komenda dla giftu "Love You" - dodaje 10 maksymalnych serc
